spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
      #   data-locations: classpath:demo_data.sql
security:
    jwt:
      secret: saopdjaspodasjASODJASOPDJASPODJASIODHASUIFHAIUDasjdhasdjhasjkdhasSDAS
      access: 3600000
      refresh: 259200000
